name: "Setup Kaitai Struct compiler"
description: "Install kaitai-struct-compiler and make it available for use in GitHub Actions"
inputs:
  kaitai-version:
    description: "Version of Kaitai Struct compiler to use"
    required: true
    default: "0.10"
runs:
  using: "composite"
  steps:
    - name: Download kaitai-struct-compiler
      run: wget --quiet https://github.com/kaitai-io/kaitai_struct_compiler/releases/download/${{ inputs.kaitai-version }}/kaitai-struct-compiler-${{ inputs.kaitai-version }}.zip
      shell: bash
    - name: Unzip kaitai-struct-compiler
      run: unzip -qq kaitai-struct-compiler-${{ inputs.kaitai-version }}.zip
      shell: bash
    - name: Set PATH for Unix
      shell: bash
      run: |
        echo "$PWD/kaitai-struct-compiler-${{ inputs.kaitai-version }}/bin" >> "$GITHUB_PATH"
      if: runner.os != 'Windows'
    - name: Set PATH for Windows
      shell: pwsh
      run: |
        echo "$Pwd\kaitai-struct-compiler-${{ inputs.kaitai-version }}/bin" >> $Env:GITHUB_PATH
      if: runner.os == 'Windows'
    - name: Print kaitai-struct-compiler version
      run: kaitai-struct-compiler-${{ inputs.kaitai-version }}/bin/kaitai-struct-compiler --version
      shell: bash
