name: "Kaitai Struct compiler"
description: "Run Kaitai Struct compiler"
inputs:
  args:
    description: "Arguments to pass to kaitai-struct-compiler"
    required: true
runs:
  using: "composite"
  steps:
    - name: Download kaitai-struct-compiler
      run: wget https://github.com/kaitai-io/kaitai_struct_compiler/releases/download/0.10/kaitai-struct-compiler-0.10.zip
      shell: bash
    - name: Unzip kaitai-struct-compiler
      run: unzip kaitai-struct-compiler-0.10.zip
      shell: bash
    - name: Run kaitai-struct-compiler
      run: kaitai-struct-compiler-0.10/bin/kaitai-struct-compiler ${{ inputs.args }}
      shell: bash
