name: "Kaitai Struct compiler"
description: "Run Kaitai Struct compiler"
inputs:
  kaitai-version:
    description: "Version of Kaitai Struct compiler to use"
    required: true
    default: "0.10"
  args:
    description: "Arguments to pass to kaitai-struct-compiler"
    required: true
runs:
  using: "composite"
  steps:
    - name: Download kaitai-struct-compiler
      run: wget --quiet https://github.com/kaitai-io/kaitai_struct_compiler/releases/download/${{ inputs.kaitai-version }}/kaitai-struct-compiler-${{ inputs.kaitai-version }}.zip
      shell: bash
    - name: Unzip kaitai-struct-compiler
      run: unzip -qq kaitai-struct-compiler-${{ inputs.kaitai-version }}.zip
      shell: bash
    - name: Run kaitai-struct-compiler
      run: kaitai-struct-compiler-${{ inputs.kaitai-version }}/bin/kaitai-struct-compiler ${{ inputs.args }}
      shell: bash
